import {test,expect} from '@playwright/test';
test('completed employment exposes ratings and related profiles',async({page})=>{
 await page.goto('/');
 await page.evaluate(()=>{(window as any).testStore.applications.a.status='completed'});
 await page.getByRole('button',{name:'מועמדים והעסקות',exact:true}).click();
 await page.getByRole('button',{name:'פרטים',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'פרטי ההתקשרות'})).toContainText('מועמד בדיקה');
 await page.getByRole('button',{name:'דרג עובד',exact:true}).click();
 await page.getByRole('combobox').selectOption('4');
 await page.getByRole('button',{name:'שמור דירוג',exact:true}).click();
 expect(await page.evaluate(()=>(window as any).rating)).toEqual({applicationId:'a',score:4});
 await page.getByRole('button',{name:'דירוגים',exact:true}).click();
 await expect(page.getByText('עסק בדיקה — 4.5 מתוך 5 · 2 דירוגים')).toBeVisible();
 await expect(page.getByText('מועמד בדיקה — 5.0 מתוך 5 · 1 דירוגים')).toBeVisible();
});
test('employer can create edit and view applicants through the active layout',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'ניהול משרות',exact:true}).click();
 await expect(page.getByRole('heading',{name:'המשרות שפרסמתי'})).toBeVisible();
 await page.getByRole('button',{name:'פרסם משרה חדשה',exact:true}).click();
 await page.locator('[name=title]').fill('משרה חדשה');
 await page.locator('[name=description]').fill('תיאור משרה חדשה');
 await page.getByRole('button',{name:'מלצרות',exact:true}).click();
 await page.getByRole('button',{name:'הבא',exact:true}).click();
 await page.locator('[name=location]').fill('תל אביב');
 await page.getByRole('button',{name:'ראשון',exact:true}).click();
 await page.getByRole('button',{name:'הבא',exact:true}).click();
 await page.locator('[name=salary]').fill('20');
 await page.getByRole('button',{name:'הבא',exact:true}).click();
 await page.locator('[name=youthLawAck]').check();
 await page.getByRole('button',{name:'פרסם משרה',exact:true}).click();
 await expect(page.getByRole('alert').first()).toContainText('שכר המינימום');
 for(let i=0;i<2;i++)await page.getByRole('button',{name:'חזרה',exact:true}).click();
 await page.locator('[name=startTime]').fill('09:00');
 await page.locator('[name=endTime]').fill('18:00');
 for(let i=0;i<2;i++)await page.getByRole('button',{name:'הבא',exact:true}).click();
 await page.getByRole('button',{name:'פרסם משרה',exact:true}).click();
 await expect(page.getByRole('alert').first()).toContainText('8 שעות');
 for(let i=0;i<2;i++)await page.getByRole('button',{name:'חזרה',exact:true}).click();
 await page.locator('[name=endTime]').fill('15:00');
 await page.getByRole('button',{name:'הבא',exact:true}).click();
 await page.locator('[name=salary]').fill('45');
 await page.getByRole('button',{name:'הבא',exact:true}).click();
 await page.getByRole('button',{name:'פרסם משרה',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByRole('heading',{name:'משרה חדשה',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>{const j=(window as any).testStore.jobs.added;return [j.minAge,j.youthLawAck,j.status]})).toEqual([16,true,'open']);
 await page.getByRole('button',{name:'ערוך',exact:true}).first().click();
 await page.locator('[name=title]').fill('משרה מעודכנת');
 for(let i=0;i<3;i++)await page.getByRole('button',{name:'הבא',exact:true}).click();
 await page.locator('[name=youthLawAck]').check();
 await page.evaluate(()=>{(window as any).failSave=true});
 page.on('dialog',d=>d.accept());
 await page.getByRole('button',{name:'שמור שינויים',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('שמירת המשרה נכשלה');
 await page.evaluate(()=>{(window as any).failSave=false});
 await page.getByRole('button',{name:'שמור שינויים',exact:true}).click();
 await expect(page.getByRole('heading',{name:'משרה מעודכנת',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'צפה במועמדים',exact:true}).last().click();
 await page.getByRole('button',{name:'צפה בפרופיל',exact:true}).click();
 await expect(page.getByText('מועמד בדיקה',{exact:true})).toBeVisible();
});
test('teen can search open a job and apply through the active layout',async({page})=>{
 await page.goto('/?role=teen');
 await expect(page.getByRole('button',{name:'ניהול משרות',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'חיפוש משרות',exact:true}).click();
 await expect(page.getByRole('heading',{name:'משרה לדוגמה',exact:true})).toBeVisible();
 await expect(page.getByText('שכר ושעות לפי חוק ✓').first()).toBeVisible();
 await page.getByRole('button',{name:'צפה בפרטים',exact:true}).first().click();
 await expect(page.getByRole('region',{name:'זכויות במשרה זו'})).toContainText('שכר ₪45 לשעה');
 await expect(page.getByRole('button',{name:'הגש מועמדות עכשיו',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'הגש מועמדות עכשיו',exact:true}).click();
 await expect(page.getByRole('button',{name:'המועמדות נשלחה ✓',exact:true})).toBeDisabled();
 expect(await page.evaluate(()=>(window as any).testStore.applications.added.jobId)).toBe('first');
 await page.getByRole('button',{name:'חזרה לחיפוש',exact:true}).click();
 await expect(page.getByRole('button',{name:'צפה בפרטים',exact:true}).first()).toBeVisible();
});
test('teen cannot apply to a job that breaks the youth law for their age',async({page})=>{
 await page.goto('/?role=teen');
 await page.getByRole('button',{name:'חיפוש משרות',exact:true}).click();
 await expect(page.getByText('לא עומד בחוק עבודת הנוער')).toBeVisible();
 await page.locator('h3:has-text("משרה לא חוקית")').locator('xpath=ancestor::div[contains(@class,"rounded-xl")][1]').getByRole('button',{name:'צפה בפרטים',exact:true}).click();
 const panel=page.getByRole('region',{name:'זכויות במשרה זו'});
 await expect(panel).toContainText('נמוך משכר המינימום לגילך');
 await expect(panel).toContainText('חורגות מהמותר לגילך');
 await expect(page.getByRole('button',{name:'הגש מועמדות עכשיו',exact:true})).toBeDisabled();
 await expect(page.getByRole('alert').first()).toContainText('שכר המינימום לגילך');
});
